/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ComponentsLayoutRouteRouteImport } from './routes/components/layout/route'
import { Route as ComponentsFormsRouteRouteImport } from './routes/components/forms/route'
import { Route as ComponentsDisplayRouteRouteImport } from './routes/components/display/route'
import { Route as HooksUseMediaQueryIndexRouteImport } from './routes/hooks/use-media-query/index'
import { Route as ComponentsThemeToggleIndexRouteImport } from './routes/components/theme-toggle/index'
import { Route as ComponentsFormsIndexRouteImport } from './routes/components/forms/index'
import { Route as ComponentsLayoutRowIndexRouteImport } from './routes/components/layout/row/index'
import { Route as ComponentsLayoutGridIndexRouteImport } from './routes/components/layout/grid/index'
import { Route as ComponentsLayoutFlexIndexRouteImport } from './routes/components/layout/flex/index'
import { Route as ComponentsLayoutColIndexRouteImport } from './routes/components/layout/col/index'
import { Route as ComponentsFormsTextFieldIndexRouteImport } from './routes/components/forms/text-field/index'
import { Route as ComponentsFormsNumberFieldIndexRouteImport } from './routes/components/forms/number-field/index'
import { Route as ComponentsFormsIconButtonIndexRouteImport } from './routes/components/forms/icon-button/index'
import { Route as ComponentsFormsCheckboxIndexRouteImport } from './routes/components/forms/checkbox/index'
import { Route as ComponentsFormsButtonIndexRouteImport } from './routes/components/forms/button/index'
import { Route as ComponentsDisplayTypographyIndexRouteImport } from './routes/components/display/typography/index'
import { Route as ComponentsDisplayTooltipIndexRouteImport } from './routes/components/display/tooltip/index'
import { Route as ComponentsDisplayLoaderIndexRouteImport } from './routes/components/display/loader/index'
import { Route as ComponentsDisplayIconIndexRouteImport } from './routes/components/display/icon/index'
import { Route as ComponentsDisplayDividerIndexRouteImport } from './routes/components/display/divider/index'
import { Route as ComponentsDisplayChipIndexRouteImport } from './routes/components/display/chip/index'
import { Route as ComponentsDisplayBadgeIndexRouteImport } from './routes/components/display/badge/index'
import { Route as ComponentsDisplayAvatarIndexRouteImport } from './routes/components/display/avatar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsLayoutRouteRoute = ComponentsLayoutRouteRouteImport.update({
  id: '/components/layout',
  path: '/components/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormsRouteRoute = ComponentsFormsRouteRouteImport.update({
  id: '/components/forms',
  path: '/components/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDisplayRouteRoute = ComponentsDisplayRouteRouteImport.update({
  id: '/components/display',
  path: '/components/display',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksUseMediaQueryIndexRoute = HooksUseMediaQueryIndexRouteImport.update({
  id: '/hooks/use-media-query/',
  path: '/hooks/use-media-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsThemeToggleIndexRoute =
  ComponentsThemeToggleIndexRouteImport.update({
    id: '/components/theme-toggle/',
    path: '/components/theme-toggle/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsFormsIndexRoute = ComponentsFormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsFormsRouteRoute,
} as any)
const ComponentsLayoutRowIndexRoute =
  ComponentsLayoutRowIndexRouteImport.update({
    id: '/row/',
    path: '/row/',
    getParentRoute: () => ComponentsLayoutRouteRoute,
  } as any)
const ComponentsLayoutGridIndexRoute =
  ComponentsLayoutGridIndexRouteImport.update({
    id: '/grid/',
    path: '/grid/',
    getParentRoute: () => ComponentsLayoutRouteRoute,
  } as any)
const ComponentsLayoutFlexIndexRoute =
  ComponentsLayoutFlexIndexRouteImport.update({
    id: '/flex/',
    path: '/flex/',
    getParentRoute: () => ComponentsLayoutRouteRoute,
  } as any)
const ComponentsLayoutColIndexRoute =
  ComponentsLayoutColIndexRouteImport.update({
    id: '/col/',
    path: '/col/',
    getParentRoute: () => ComponentsLayoutRouteRoute,
  } as any)
const ComponentsFormsTextFieldIndexRoute =
  ComponentsFormsTextFieldIndexRouteImport.update({
    id: '/text-field/',
    path: '/text-field/',
    getParentRoute: () => ComponentsFormsRouteRoute,
  } as any)
const ComponentsFormsNumberFieldIndexRoute =
  ComponentsFormsNumberFieldIndexRouteImport.update({
    id: '/number-field/',
    path: '/number-field/',
    getParentRoute: () => ComponentsFormsRouteRoute,
  } as any)
const ComponentsFormsIconButtonIndexRoute =
  ComponentsFormsIconButtonIndexRouteImport.update({
    id: '/icon-button/',
    path: '/icon-button/',
    getParentRoute: () => ComponentsFormsRouteRoute,
  } as any)
const ComponentsFormsCheckboxIndexRoute =
  ComponentsFormsCheckboxIndexRouteImport.update({
    id: '/checkbox/',
    path: '/checkbox/',
    getParentRoute: () => ComponentsFormsRouteRoute,
  } as any)
const ComponentsFormsButtonIndexRoute =
  ComponentsFormsButtonIndexRouteImport.update({
    id: '/button/',
    path: '/button/',
    getParentRoute: () => ComponentsFormsRouteRoute,
  } as any)
const ComponentsDisplayTypographyIndexRoute =
  ComponentsDisplayTypographyIndexRouteImport.update({
    id: '/typography/',
    path: '/typography/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayTooltipIndexRoute =
  ComponentsDisplayTooltipIndexRouteImport.update({
    id: '/tooltip/',
    path: '/tooltip/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayLoaderIndexRoute =
  ComponentsDisplayLoaderIndexRouteImport.update({
    id: '/loader/',
    path: '/loader/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayIconIndexRoute =
  ComponentsDisplayIconIndexRouteImport.update({
    id: '/icon/',
    path: '/icon/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayDividerIndexRoute =
  ComponentsDisplayDividerIndexRouteImport.update({
    id: '/divider/',
    path: '/divider/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayChipIndexRoute =
  ComponentsDisplayChipIndexRouteImport.update({
    id: '/chip/',
    path: '/chip/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayBadgeIndexRoute =
  ComponentsDisplayBadgeIndexRouteImport.update({
    id: '/badge/',
    path: '/badge/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)
const ComponentsDisplayAvatarIndexRoute =
  ComponentsDisplayAvatarIndexRouteImport.update({
    id: '/avatar/',
    path: '/avatar/',
    getParentRoute: () => ComponentsDisplayRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/display': typeof ComponentsDisplayRouteRouteWithChildren
  '/components/forms': typeof ComponentsFormsRouteRouteWithChildren
  '/components/layout': typeof ComponentsLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/components/forms/': typeof ComponentsFormsIndexRoute
  '/components/theme-toggle/': typeof ComponentsThemeToggleIndexRoute
  '/hooks/use-media-query/': typeof HooksUseMediaQueryIndexRoute
  '/components/display/avatar/': typeof ComponentsDisplayAvatarIndexRoute
  '/components/display/badge/': typeof ComponentsDisplayBadgeIndexRoute
  '/components/display/chip/': typeof ComponentsDisplayChipIndexRoute
  '/components/display/divider/': typeof ComponentsDisplayDividerIndexRoute
  '/components/display/icon/': typeof ComponentsDisplayIconIndexRoute
  '/components/display/loader/': typeof ComponentsDisplayLoaderIndexRoute
  '/components/display/tooltip/': typeof ComponentsDisplayTooltipIndexRoute
  '/components/display/typography/': typeof ComponentsDisplayTypographyIndexRoute
  '/components/forms/button/': typeof ComponentsFormsButtonIndexRoute
  '/components/forms/checkbox/': typeof ComponentsFormsCheckboxIndexRoute
  '/components/forms/icon-button/': typeof ComponentsFormsIconButtonIndexRoute
  '/components/forms/number-field/': typeof ComponentsFormsNumberFieldIndexRoute
  '/components/forms/text-field/': typeof ComponentsFormsTextFieldIndexRoute
  '/components/layout/col/': typeof ComponentsLayoutColIndexRoute
  '/components/layout/flex/': typeof ComponentsLayoutFlexIndexRoute
  '/components/layout/grid/': typeof ComponentsLayoutGridIndexRoute
  '/components/layout/row/': typeof ComponentsLayoutRowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/display': typeof ComponentsDisplayRouteRouteWithChildren
  '/components/layout': typeof ComponentsLayoutRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/components/forms': typeof ComponentsFormsIndexRoute
  '/components/theme-toggle': typeof ComponentsThemeToggleIndexRoute
  '/hooks/use-media-query': typeof HooksUseMediaQueryIndexRoute
  '/components/display/avatar': typeof ComponentsDisplayAvatarIndexRoute
  '/components/display/badge': typeof ComponentsDisplayBadgeIndexRoute
  '/components/display/chip': typeof ComponentsDisplayChipIndexRoute
  '/components/display/divider': typeof ComponentsDisplayDividerIndexRoute
  '/components/display/icon': typeof ComponentsDisplayIconIndexRoute
  '/components/display/loader': typeof ComponentsDisplayLoaderIndexRoute
  '/components/display/tooltip': typeof ComponentsDisplayTooltipIndexRoute
  '/components/display/typography': typeof ComponentsDisplayTypographyIndexRoute
  '/components/forms/button': typeof ComponentsFormsButtonIndexRoute
  '/components/forms/checkbox': typeof ComponentsFormsCheckboxIndexRoute
  '/components/forms/icon-button': typeof ComponentsFormsIconButtonIndexRoute
  '/components/forms/number-field': typeof ComponentsFormsNumberFieldIndexRoute
  '/components/forms/text-field': typeof ComponentsFormsTextFieldIndexRoute
  '/components/layout/col': typeof ComponentsLayoutColIndexRoute
  '/components/layout/flex': typeof ComponentsLayoutFlexIndexRoute
  '/components/layout/grid': typeof ComponentsLayoutGridIndexRoute
  '/components/layout/row': typeof ComponentsLayoutRowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/display': typeof ComponentsDisplayRouteRouteWithChildren
  '/components/forms': typeof ComponentsFormsRouteRouteWithChildren
  '/components/layout': typeof ComponentsLayoutRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/components/forms/': typeof ComponentsFormsIndexRoute
  '/components/theme-toggle/': typeof ComponentsThemeToggleIndexRoute
  '/hooks/use-media-query/': typeof HooksUseMediaQueryIndexRoute
  '/components/display/avatar/': typeof ComponentsDisplayAvatarIndexRoute
  '/components/display/badge/': typeof ComponentsDisplayBadgeIndexRoute
  '/components/display/chip/': typeof ComponentsDisplayChipIndexRoute
  '/components/display/divider/': typeof ComponentsDisplayDividerIndexRoute
  '/components/display/icon/': typeof ComponentsDisplayIconIndexRoute
  '/components/display/loader/': typeof ComponentsDisplayLoaderIndexRoute
  '/components/display/tooltip/': typeof ComponentsDisplayTooltipIndexRoute
  '/components/display/typography/': typeof ComponentsDisplayTypographyIndexRoute
  '/components/forms/button/': typeof ComponentsFormsButtonIndexRoute
  '/components/forms/checkbox/': typeof ComponentsFormsCheckboxIndexRoute
  '/components/forms/icon-button/': typeof ComponentsFormsIconButtonIndexRoute
  '/components/forms/number-field/': typeof ComponentsFormsNumberFieldIndexRoute
  '/components/forms/text-field/': typeof ComponentsFormsTextFieldIndexRoute
  '/components/layout/col/': typeof ComponentsLayoutColIndexRoute
  '/components/layout/flex/': typeof ComponentsLayoutFlexIndexRoute
  '/components/layout/grid/': typeof ComponentsLayoutGridIndexRoute
  '/components/layout/row/': typeof ComponentsLayoutRowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/display'
    | '/components/forms'
    | '/components/layout'
    | '/login/'
    | '/components/forms/'
    | '/components/theme-toggle/'
    | '/hooks/use-media-query/'
    | '/components/display/avatar/'
    | '/components/display/badge/'
    | '/components/display/chip/'
    | '/components/display/divider/'
    | '/components/display/icon/'
    | '/components/display/loader/'
    | '/components/display/tooltip/'
    | '/components/display/typography/'
    | '/components/forms/button/'
    | '/components/forms/checkbox/'
    | '/components/forms/icon-button/'
    | '/components/forms/number-field/'
    | '/components/forms/text-field/'
    | '/components/layout/col/'
    | '/components/layout/flex/'
    | '/components/layout/grid/'
    | '/components/layout/row/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/display'
    | '/components/layout'
    | '/login'
    | '/components/forms'
    | '/components/theme-toggle'
    | '/hooks/use-media-query'
    | '/components/display/avatar'
    | '/components/display/badge'
    | '/components/display/chip'
    | '/components/display/divider'
    | '/components/display/icon'
    | '/components/display/loader'
    | '/components/display/tooltip'
    | '/components/display/typography'
    | '/components/forms/button'
    | '/components/forms/checkbox'
    | '/components/forms/icon-button'
    | '/components/forms/number-field'
    | '/components/forms/text-field'
    | '/components/layout/col'
    | '/components/layout/flex'
    | '/components/layout/grid'
    | '/components/layout/row'
  id:
    | '__root__'
    | '/'
    | '/components/display'
    | '/components/forms'
    | '/components/layout'
    | '/login/'
    | '/components/forms/'
    | '/components/theme-toggle/'
    | '/hooks/use-media-query/'
    | '/components/display/avatar/'
    | '/components/display/badge/'
    | '/components/display/chip/'
    | '/components/display/divider/'
    | '/components/display/icon/'
    | '/components/display/loader/'
    | '/components/display/tooltip/'
    | '/components/display/typography/'
    | '/components/forms/button/'
    | '/components/forms/checkbox/'
    | '/components/forms/icon-button/'
    | '/components/forms/number-field/'
    | '/components/forms/text-field/'
    | '/components/layout/col/'
    | '/components/layout/flex/'
    | '/components/layout/grid/'
    | '/components/layout/row/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsDisplayRouteRoute: typeof ComponentsDisplayRouteRouteWithChildren
  ComponentsFormsRouteRoute: typeof ComponentsFormsRouteRouteWithChildren
  ComponentsLayoutRouteRoute: typeof ComponentsLayoutRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ComponentsThemeToggleIndexRoute: typeof ComponentsThemeToggleIndexRoute
  HooksUseMediaQueryIndexRoute: typeof HooksUseMediaQueryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/layout': {
      id: '/components/layout'
      path: '/components/layout'
      fullPath: '/components/layout'
      preLoaderRoute: typeof ComponentsLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms': {
      id: '/components/forms'
      path: '/components/forms'
      fullPath: '/components/forms'
      preLoaderRoute: typeof ComponentsFormsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/display': {
      id: '/components/display'
      path: '/components/display'
      fullPath: '/components/display'
      preLoaderRoute: typeof ComponentsDisplayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/use-media-query/': {
      id: '/hooks/use-media-query/'
      path: '/hooks/use-media-query'
      fullPath: '/hooks/use-media-query/'
      preLoaderRoute: typeof HooksUseMediaQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/theme-toggle/': {
      id: '/components/theme-toggle/'
      path: '/components/theme-toggle'
      fullPath: '/components/theme-toggle/'
      preLoaderRoute: typeof ComponentsThemeToggleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms/': {
      id: '/components/forms/'
      path: '/'
      fullPath: '/components/forms/'
      preLoaderRoute: typeof ComponentsFormsIndexRouteImport
      parentRoute: typeof ComponentsFormsRouteRoute
    }
    '/components/layout/row/': {
      id: '/components/layout/row/'
      path: '/row'
      fullPath: '/components/layout/row/'
      preLoaderRoute: typeof ComponentsLayoutRowIndexRouteImport
      parentRoute: typeof ComponentsLayoutRouteRoute
    }
    '/components/layout/grid/': {
      id: '/components/layout/grid/'
      path: '/grid'
      fullPath: '/components/layout/grid/'
      preLoaderRoute: typeof ComponentsLayoutGridIndexRouteImport
      parentRoute: typeof ComponentsLayoutRouteRoute
    }
    '/components/layout/flex/': {
      id: '/components/layout/flex/'
      path: '/flex'
      fullPath: '/components/layout/flex/'
      preLoaderRoute: typeof ComponentsLayoutFlexIndexRouteImport
      parentRoute: typeof ComponentsLayoutRouteRoute
    }
    '/components/layout/col/': {
      id: '/components/layout/col/'
      path: '/col'
      fullPath: '/components/layout/col/'
      preLoaderRoute: typeof ComponentsLayoutColIndexRouteImport
      parentRoute: typeof ComponentsLayoutRouteRoute
    }
    '/components/forms/text-field/': {
      id: '/components/forms/text-field/'
      path: '/text-field'
      fullPath: '/components/forms/text-field/'
      preLoaderRoute: typeof ComponentsFormsTextFieldIndexRouteImport
      parentRoute: typeof ComponentsFormsRouteRoute
    }
    '/components/forms/number-field/': {
      id: '/components/forms/number-field/'
      path: '/number-field'
      fullPath: '/components/forms/number-field/'
      preLoaderRoute: typeof ComponentsFormsNumberFieldIndexRouteImport
      parentRoute: typeof ComponentsFormsRouteRoute
    }
    '/components/forms/icon-button/': {
      id: '/components/forms/icon-button/'
      path: '/icon-button'
      fullPath: '/components/forms/icon-button/'
      preLoaderRoute: typeof ComponentsFormsIconButtonIndexRouteImport
      parentRoute: typeof ComponentsFormsRouteRoute
    }
    '/components/forms/checkbox/': {
      id: '/components/forms/checkbox/'
      path: '/checkbox'
      fullPath: '/components/forms/checkbox/'
      preLoaderRoute: typeof ComponentsFormsCheckboxIndexRouteImport
      parentRoute: typeof ComponentsFormsRouteRoute
    }
    '/components/forms/button/': {
      id: '/components/forms/button/'
      path: '/button'
      fullPath: '/components/forms/button/'
      preLoaderRoute: typeof ComponentsFormsButtonIndexRouteImport
      parentRoute: typeof ComponentsFormsRouteRoute
    }
    '/components/display/typography/': {
      id: '/components/display/typography/'
      path: '/typography'
      fullPath: '/components/display/typography/'
      preLoaderRoute: typeof ComponentsDisplayTypographyIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/tooltip/': {
      id: '/components/display/tooltip/'
      path: '/tooltip'
      fullPath: '/components/display/tooltip/'
      preLoaderRoute: typeof ComponentsDisplayTooltipIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/loader/': {
      id: '/components/display/loader/'
      path: '/loader'
      fullPath: '/components/display/loader/'
      preLoaderRoute: typeof ComponentsDisplayLoaderIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/icon/': {
      id: '/components/display/icon/'
      path: '/icon'
      fullPath: '/components/display/icon/'
      preLoaderRoute: typeof ComponentsDisplayIconIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/divider/': {
      id: '/components/display/divider/'
      path: '/divider'
      fullPath: '/components/display/divider/'
      preLoaderRoute: typeof ComponentsDisplayDividerIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/chip/': {
      id: '/components/display/chip/'
      path: '/chip'
      fullPath: '/components/display/chip/'
      preLoaderRoute: typeof ComponentsDisplayChipIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/badge/': {
      id: '/components/display/badge/'
      path: '/badge'
      fullPath: '/components/display/badge/'
      preLoaderRoute: typeof ComponentsDisplayBadgeIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
    '/components/display/avatar/': {
      id: '/components/display/avatar/'
      path: '/avatar'
      fullPath: '/components/display/avatar/'
      preLoaderRoute: typeof ComponentsDisplayAvatarIndexRouteImport
      parentRoute: typeof ComponentsDisplayRouteRoute
    }
  }
}

interface ComponentsDisplayRouteRouteChildren {
  ComponentsDisplayAvatarIndexRoute: typeof ComponentsDisplayAvatarIndexRoute
  ComponentsDisplayBadgeIndexRoute: typeof ComponentsDisplayBadgeIndexRoute
  ComponentsDisplayChipIndexRoute: typeof ComponentsDisplayChipIndexRoute
  ComponentsDisplayDividerIndexRoute: typeof ComponentsDisplayDividerIndexRoute
  ComponentsDisplayIconIndexRoute: typeof ComponentsDisplayIconIndexRoute
  ComponentsDisplayLoaderIndexRoute: typeof ComponentsDisplayLoaderIndexRoute
  ComponentsDisplayTooltipIndexRoute: typeof ComponentsDisplayTooltipIndexRoute
  ComponentsDisplayTypographyIndexRoute: typeof ComponentsDisplayTypographyIndexRoute
}

const ComponentsDisplayRouteRouteChildren: ComponentsDisplayRouteRouteChildren =
  {
    ComponentsDisplayAvatarIndexRoute: ComponentsDisplayAvatarIndexRoute,
    ComponentsDisplayBadgeIndexRoute: ComponentsDisplayBadgeIndexRoute,
    ComponentsDisplayChipIndexRoute: ComponentsDisplayChipIndexRoute,
    ComponentsDisplayDividerIndexRoute: ComponentsDisplayDividerIndexRoute,
    ComponentsDisplayIconIndexRoute: ComponentsDisplayIconIndexRoute,
    ComponentsDisplayLoaderIndexRoute: ComponentsDisplayLoaderIndexRoute,
    ComponentsDisplayTooltipIndexRoute: ComponentsDisplayTooltipIndexRoute,
    ComponentsDisplayTypographyIndexRoute:
      ComponentsDisplayTypographyIndexRoute,
  }

const ComponentsDisplayRouteRouteWithChildren =
  ComponentsDisplayRouteRoute._addFileChildren(
    ComponentsDisplayRouteRouteChildren,
  )

interface ComponentsFormsRouteRouteChildren {
  ComponentsFormsIndexRoute: typeof ComponentsFormsIndexRoute
  ComponentsFormsButtonIndexRoute: typeof ComponentsFormsButtonIndexRoute
  ComponentsFormsCheckboxIndexRoute: typeof ComponentsFormsCheckboxIndexRoute
  ComponentsFormsIconButtonIndexRoute: typeof ComponentsFormsIconButtonIndexRoute
  ComponentsFormsNumberFieldIndexRoute: typeof ComponentsFormsNumberFieldIndexRoute
  ComponentsFormsTextFieldIndexRoute: typeof ComponentsFormsTextFieldIndexRoute
}

const ComponentsFormsRouteRouteChildren: ComponentsFormsRouteRouteChildren = {
  ComponentsFormsIndexRoute: ComponentsFormsIndexRoute,
  ComponentsFormsButtonIndexRoute: ComponentsFormsButtonIndexRoute,
  ComponentsFormsCheckboxIndexRoute: ComponentsFormsCheckboxIndexRoute,
  ComponentsFormsIconButtonIndexRoute: ComponentsFormsIconButtonIndexRoute,
  ComponentsFormsNumberFieldIndexRoute: ComponentsFormsNumberFieldIndexRoute,
  ComponentsFormsTextFieldIndexRoute: ComponentsFormsTextFieldIndexRoute,
}

const ComponentsFormsRouteRouteWithChildren =
  ComponentsFormsRouteRoute._addFileChildren(ComponentsFormsRouteRouteChildren)

interface ComponentsLayoutRouteRouteChildren {
  ComponentsLayoutColIndexRoute: typeof ComponentsLayoutColIndexRoute
  ComponentsLayoutFlexIndexRoute: typeof ComponentsLayoutFlexIndexRoute
  ComponentsLayoutGridIndexRoute: typeof ComponentsLayoutGridIndexRoute
  ComponentsLayoutRowIndexRoute: typeof ComponentsLayoutRowIndexRoute
}

const ComponentsLayoutRouteRouteChildren: ComponentsLayoutRouteRouteChildren = {
  ComponentsLayoutColIndexRoute: ComponentsLayoutColIndexRoute,
  ComponentsLayoutFlexIndexRoute: ComponentsLayoutFlexIndexRoute,
  ComponentsLayoutGridIndexRoute: ComponentsLayoutGridIndexRoute,
  ComponentsLayoutRowIndexRoute: ComponentsLayoutRowIndexRoute,
}

const ComponentsLayoutRouteRouteWithChildren =
  ComponentsLayoutRouteRoute._addFileChildren(
    ComponentsLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsDisplayRouteRoute: ComponentsDisplayRouteRouteWithChildren,
  ComponentsFormsRouteRoute: ComponentsFormsRouteRouteWithChildren,
  ComponentsLayoutRouteRoute: ComponentsLayoutRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ComponentsThemeToggleIndexRoute: ComponentsThemeToggleIndexRoute,
  HooksUseMediaQueryIndexRoute: HooksUseMediaQueryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
