/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsThemeToggleRouteImport } from './routes/components/theme-toggle'
import { Route as ComponentsFormsTextFieldRouteImport } from './routes/components/forms/text-field'
import { Route as ComponentsFormsNumberFieldRouteImport } from './routes/components/forms/number-field'
import { Route as ComponentsFormsIconButtonRouteImport } from './routes/components/forms/icon-button'
import { Route as ComponentsFormsCheckboxRouteImport } from './routes/components/forms/checkbox'
import { Route as ComponentsFormsButtonRouteImport } from './routes/components/forms/button'
import { Route as ComponentsDisplayTypographyRouteImport } from './routes/components/display/typography'
import { Route as ComponentsDisplayIconRouteImport } from './routes/components/display/icon'
import { Route as ComponentsDisplayLoaderIndexRouteImport } from './routes/components/display/loader/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsThemeToggleRoute = ComponentsThemeToggleRouteImport.update({
  id: '/components/theme-toggle',
  path: '/components/theme-toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormsTextFieldRoute =
  ComponentsFormsTextFieldRouteImport.update({
    id: '/components/forms/text-field',
    path: '/components/forms/text-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsFormsNumberFieldRoute =
  ComponentsFormsNumberFieldRouteImport.update({
    id: '/components/forms/number-field',
    path: '/components/forms/number-field',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsFormsIconButtonRoute =
  ComponentsFormsIconButtonRouteImport.update({
    id: '/components/forms/icon-button',
    path: '/components/forms/icon-button',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsFormsCheckboxRoute = ComponentsFormsCheckboxRouteImport.update({
  id: '/components/forms/checkbox',
  path: '/components/forms/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormsButtonRoute = ComponentsFormsButtonRouteImport.update({
  id: '/components/forms/button',
  path: '/components/forms/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDisplayTypographyRoute =
  ComponentsDisplayTypographyRouteImport.update({
    id: '/components/display/typography',
    path: '/components/display/typography',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsDisplayIconRoute = ComponentsDisplayIconRouteImport.update({
  id: '/components/display/icon',
  path: '/components/display/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDisplayLoaderIndexRoute =
  ComponentsDisplayLoaderIndexRouteImport.update({
    id: '/components/display/loader/',
    path: '/components/display/loader/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/theme-toggle': typeof ComponentsThemeToggleRoute
  '/components/display/icon': typeof ComponentsDisplayIconRoute
  '/components/display/typography': typeof ComponentsDisplayTypographyRoute
  '/components/forms/button': typeof ComponentsFormsButtonRoute
  '/components/forms/checkbox': typeof ComponentsFormsCheckboxRoute
  '/components/forms/icon-button': typeof ComponentsFormsIconButtonRoute
  '/components/forms/number-field': typeof ComponentsFormsNumberFieldRoute
  '/components/forms/text-field': typeof ComponentsFormsTextFieldRoute
  '/components/display/loader/': typeof ComponentsDisplayLoaderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/theme-toggle': typeof ComponentsThemeToggleRoute
  '/components/display/icon': typeof ComponentsDisplayIconRoute
  '/components/display/typography': typeof ComponentsDisplayTypographyRoute
  '/components/forms/button': typeof ComponentsFormsButtonRoute
  '/components/forms/checkbox': typeof ComponentsFormsCheckboxRoute
  '/components/forms/icon-button': typeof ComponentsFormsIconButtonRoute
  '/components/forms/number-field': typeof ComponentsFormsNumberFieldRoute
  '/components/forms/text-field': typeof ComponentsFormsTextFieldRoute
  '/components/display/loader': typeof ComponentsDisplayLoaderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/theme-toggle': typeof ComponentsThemeToggleRoute
  '/components/display/icon': typeof ComponentsDisplayIconRoute
  '/components/display/typography': typeof ComponentsDisplayTypographyRoute
  '/components/forms/button': typeof ComponentsFormsButtonRoute
  '/components/forms/checkbox': typeof ComponentsFormsCheckboxRoute
  '/components/forms/icon-button': typeof ComponentsFormsIconButtonRoute
  '/components/forms/number-field': typeof ComponentsFormsNumberFieldRoute
  '/components/forms/text-field': typeof ComponentsFormsTextFieldRoute
  '/components/display/loader/': typeof ComponentsDisplayLoaderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/theme-toggle'
    | '/components/display/icon'
    | '/components/display/typography'
    | '/components/forms/button'
    | '/components/forms/checkbox'
    | '/components/forms/icon-button'
    | '/components/forms/number-field'
    | '/components/forms/text-field'
    | '/components/display/loader/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/theme-toggle'
    | '/components/display/icon'
    | '/components/display/typography'
    | '/components/forms/button'
    | '/components/forms/checkbox'
    | '/components/forms/icon-button'
    | '/components/forms/number-field'
    | '/components/forms/text-field'
    | '/components/display/loader'
  id:
    | '__root__'
    | '/'
    | '/components/theme-toggle'
    | '/components/display/icon'
    | '/components/display/typography'
    | '/components/forms/button'
    | '/components/forms/checkbox'
    | '/components/forms/icon-button'
    | '/components/forms/number-field'
    | '/components/forms/text-field'
    | '/components/display/loader/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsThemeToggleRoute: typeof ComponentsThemeToggleRoute
  ComponentsDisplayIconRoute: typeof ComponentsDisplayIconRoute
  ComponentsDisplayTypographyRoute: typeof ComponentsDisplayTypographyRoute
  ComponentsFormsButtonRoute: typeof ComponentsFormsButtonRoute
  ComponentsFormsCheckboxRoute: typeof ComponentsFormsCheckboxRoute
  ComponentsFormsIconButtonRoute: typeof ComponentsFormsIconButtonRoute
  ComponentsFormsNumberFieldRoute: typeof ComponentsFormsNumberFieldRoute
  ComponentsFormsTextFieldRoute: typeof ComponentsFormsTextFieldRoute
  ComponentsDisplayLoaderIndexRoute: typeof ComponentsDisplayLoaderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/theme-toggle': {
      id: '/components/theme-toggle'
      path: '/components/theme-toggle'
      fullPath: '/components/theme-toggle'
      preLoaderRoute: typeof ComponentsThemeToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms/text-field': {
      id: '/components/forms/text-field'
      path: '/components/forms/text-field'
      fullPath: '/components/forms/text-field'
      preLoaderRoute: typeof ComponentsFormsTextFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms/number-field': {
      id: '/components/forms/number-field'
      path: '/components/forms/number-field'
      fullPath: '/components/forms/number-field'
      preLoaderRoute: typeof ComponentsFormsNumberFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms/icon-button': {
      id: '/components/forms/icon-button'
      path: '/components/forms/icon-button'
      fullPath: '/components/forms/icon-button'
      preLoaderRoute: typeof ComponentsFormsIconButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms/checkbox': {
      id: '/components/forms/checkbox'
      path: '/components/forms/checkbox'
      fullPath: '/components/forms/checkbox'
      preLoaderRoute: typeof ComponentsFormsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/forms/button': {
      id: '/components/forms/button'
      path: '/components/forms/button'
      fullPath: '/components/forms/button'
      preLoaderRoute: typeof ComponentsFormsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/display/typography': {
      id: '/components/display/typography'
      path: '/components/display/typography'
      fullPath: '/components/display/typography'
      preLoaderRoute: typeof ComponentsDisplayTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/display/icon': {
      id: '/components/display/icon'
      path: '/components/display/icon'
      fullPath: '/components/display/icon'
      preLoaderRoute: typeof ComponentsDisplayIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/display/loader/': {
      id: '/components/display/loader/'
      path: '/components/display/loader'
      fullPath: '/components/display/loader/'
      preLoaderRoute: typeof ComponentsDisplayLoaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsThemeToggleRoute: ComponentsThemeToggleRoute,
  ComponentsDisplayIconRoute: ComponentsDisplayIconRoute,
  ComponentsDisplayTypographyRoute: ComponentsDisplayTypographyRoute,
  ComponentsFormsButtonRoute: ComponentsFormsButtonRoute,
  ComponentsFormsCheckboxRoute: ComponentsFormsCheckboxRoute,
  ComponentsFormsIconButtonRoute: ComponentsFormsIconButtonRoute,
  ComponentsFormsNumberFieldRoute: ComponentsFormsNumberFieldRoute,
  ComponentsFormsTextFieldRoute: ComponentsFormsTextFieldRoute,
  ComponentsDisplayLoaderIndexRoute: ComponentsDisplayLoaderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
